### ISSUE TITLE
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

### ISSUE THREAD

**Issue by abdoelsayed2016** [BlackStar1313/ICDAR-2019-RRC-SROIE#2]
Traceback (most recent call last):
  File "keyword_information_extraction/train.py", line 394, in <module>
    main()
  File "keyword_information_extraction/train.py", line 166, in main
    logger=logger,train_dataset= train_dataset)
  File "keyword_information_extraction/train.py", line 259, in train
    predictions = model(text_features)
  File "/home/ubuntu/anaconda3/envs/app/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/ICDAR-2019-RRC-SROIE-master-1/keyword_information_extraction/model/charlm/charlm_cnn_highway_lstm.py", line 145, in forward
    cnn_features = torch.cat(pool_layers, dim=1)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by NjoyimPeguy** [comment]
@abdoelsayed2016 which dataset are you using? The one provided? Because this error means that pool layers are tensors of single dimension.

**Comment by abdoelsayed2016** [comment]
custom dataset it works fine when the number of classes more than 4 but when it change it to 3 classes it appear this error.

and i am wondering, the training start normarlly until epoch 80.

**Comment by NjoyimPeguy** [comment]
Well this is weird...I need more details about your custom dataset, code, etc. As it is supposed to work for any number of classes >= 2, I am wondering what you have changed.
